[package]
name = "chusst"
version = "0.7.0"
description = "A simple chess engine in Rust"
authors = ["Oriol Arcas"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.0.4"
atty = "0.2.14"
futures = "0.3.28"
async-std = "1.12.0"
rust-fsm = "0.6.1"
crossbeam-channel = "0.5.8"

[dev-dependencies]
bencher = "0.1.5"

[[bin]]
name = "chusst-uci"
path = "src/bin/uci/main.rs"

[features]
# DO NOT set 'default', breaks production build

# Build with this feature to print the search tree to stdout
verbose-search = []

# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[[bench]]
name = "search"
harness = false
