name: Test

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y
        libwebkit2gtk-4.0-dev
        build-essential
        curl
        wget
        file
        libssl-dev
        libgtk-3-dev
        libayatana-appindicator3-dev
        librsvg2-dev
    - name: Build
      working-directory: ./src-tauri
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./src-tauri
      run: cargo test --verbose
    - name: Build
      working-directory: ./src-tauri
      run: cargo tauri build -b deb
      if: startsWith(github.ref, 'refs/tags/')
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./src-tauri/target/bundle/deb/*.deb
